#!/bin/env python

import socket, struct
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect(('127.0.0.1', 1337))
m = 'hello world'
version = 1
type = 1
paylen = len(m)
data = struct.pack('!BBH', version, type, paylen)

while 1:
  print(s.send(data + m))
	Rdata = ''
	while len(Rdata) < 4:
	  Rdata += s.recv(4)
	version, type, paylen = struct.unpack('!BBH', Rdata)
	print(version, type, paylen)
	print(s.recv(paylen))
